#include <map>

enum Case 
{
	ONE_FRIENDLY,	ONE_FRIENDLY_BLOCKED,
	ONE_ENEMY,		ONE_ENEMY_BLOCKED,
	TWO_FRIENDLY,	TWO_FRIENDLY_BLOCKED,
	TWO_ENEMY,		TWO_ENEMY_BLOCKED,
	THREE_FRIENDLY, THREE_FRIENDLY_BLOCKED,
	THREE_ENEMY,	THREE_ENEMY_BLOCKED,
	FOUR_FRIENDLY,
	FOUR_ENEMY
};

class Heuristic
{
public:
	int getRank(const Case event);
private:
	std::map<Case, int> ranks = {
		{ONE_FRIENDLY, 5},		{ONE_FRIENDLY_BLOCKED, 2},
		{ONE_ENEMY, 6},			{ONE_ENEMY_BLOCKED, 3},
		{TWO_FRIENDLY, 10},		{TWO_FRIENDLY_BLOCKED, 5},
		{TWO_ENEMY, 15},		{TWO_ENEMY_BLOCKED, 6},
		{THREE_FRIENDLY, 100},	{THREE_FRIENDLY_BLOCKED, 10},
		{THREE_ENEMY, 50},		{THREE_ENEMY_BLOCKED, 15},
		{FOUR_FRIENDLY, 1000},
		{FOUR_ENEMY, 500}
	}
};